force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Relations__c/Public_Relations__c.object-meta.xml
<CustomObject>
    <label>Public Relation</label>
    <nameField>
        <label>PR event name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Relations__c/fields/Idol__c.field-meta.xml
<CustomField>
    <fullName>Idol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Idol</label>
    <referenceTo>Idol__c</referenceTo>
    <relationshipLabel>Public Relations</relationshipLabel>
    <relationshipName>Public_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/pickIdolsTest.cls
@isTest
private class pickIdolsTest {
    
    // test for single record - getIdolNames
    @isTest
    static void getIdolNamesWithOneRecord(){
        // Test data setup
        List<SelectOption> options = pITestDataFactory.createOptionsWithIdols(1);
        
        // Perform Test
        Test.startTest();
        pickIdols_CC pickIdols = new pickIdols_CC();
        List<SelectOption> optionList = pickIdols.getIdolNames();
        Test.stopTest();
        
        
        
        // Verify the test
        System.assertEquals(options, optionList );
    }
    
    
    
    // test for bulk records - getIdolNames
    @isTest
    static void getIdolNamesWithBulkRecords(){
        // Test data setup
        List<SelectOption> options = pITestDataFactory.createOptionsWithIdols(200);
        
        // Perform Test
        Test.startTest();
        pickIdols_CC pickIdols = new pickIdols_CC();
        List<SelectOption> optionList = pickIdols.getIdolNames();
        Test.stopTest();
        
        
        
        // Verify the test
        System.assertEquals(options, optionList );
    }
    
    
    
    // test for single record - showTable
    @isTest
    static void showTableWIthOneRecord(){
        //Test Data Setup
        List<Idol__c> idols = pITestDataFactory.createIdols(1);
        Idol__c idolId = [SELECT id FROM Idol__C Limit 1];
        Id idolIID = idolId.Id;
        String idolIdString = String.valueOf(idolIID);


        List<Public_Relations__c> prExpected = pITestDataFactory.createPR(1, idolIId);
        //List<Public_Relations__c> pr = [SELECT Name FROM Public_Relations__c];

        
        
        // Perform Test
        
        Test.startTest();
        
        pickIdols_CC pickIdols = new pickIdols_CC();
        pickIdols.selectedIdolId = idolIdString;
        pickIdols.ShowTable();
        List<Public_Relations__c> prActual = pickIdols.prRecords;
        Test.stopTest();
        
        
        //Verify Test
        System.debug('expected' + prExpected);
        System.debug('actual' + prActual);
 
        System.assertEquals(prExpected, prActual);
        
        
    }
    
    
    
    // test for bulk - showTable
    @isTest
    static void showTableWIthBulkRecord(){
        //Test Data Setup
        List<Idol__c> idols = pITestDataFactory.createIdols(200);
        Idol__c idolId = [SELECT id FROM Idol__C Limit 1];
        Id idolIID = idolId.Id;
        String idolIdString = String.valueOf(idolIID);


        List<Public_Relations__c> prExpected = pITestDataFactory.createPR(200, idolIId);
        //List<Public_Relations__c> pr = [SELECT Name FROM Public_Relations__c];

        
        
        // Perform Test
        
        Test.startTest();
        
        pickIdols_CC pickIdols = new pickIdols_CC();
        pickIdols.selectedIdolId = idolIdString;
        pickIdols.ShowTable();
        List<Public_Relations__c> prActual = pickIdols.prRecords;
        Test.stopTest();
        
        
        //Verify Test
        System.debug('expected' + prExpected);
        System.debug('actual' + prActual);
 
        System.assertEquals(prExpected, prActual);
        
    }
    
    
}