force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol__c/fields/Assigned_Location__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Idols</relationshipLabel>
    <relationshipName>Idols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Idol__c/fields/Date_recruited__c.field-meta.xml
<CustomField>
    <fullName>Date_recruited__c</fullName>
    <label>Date recruited</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Idol__c/fields/Idol_Pay__c.field-meta.xml
<CustomField>
    <fullName>Idol_Pay__c</fullName>
    <label>Idol Pay</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Idol__c/fields/Idol_phone__c.field-meta.xml
<CustomField>
    <fullName>Idol_phone__c</fullName>
    <label>Idol phone number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Idol__c/recordTypes/Idol.recordType-meta.xml
<RecordType>
    <fullName>Idol</fullName>
    <active>true</active>
    <description>Fully fledged Idols that have debuted</description>
    <label>Idol</label>
</RecordType>

force-app/main/default/classes/IdolControllerExtension.cls
public with sharing class IdolControllerExtension {
    
    Idol__c idol;
    public IdolControllerExtension(ApexPages.StandardController controller){
        this.idol = (Idol__c) controller.getRecord();
    }


    private String sortOrder = 'Name';
    
    public List<Idol__c> getIdols() {
        String retrieveFields = 'Name, Id, Idol_Phone__c, Assigned_Location__c, Date_recruited__c, Idol_Pay__c';
        String fieldLocation = 'Idol__c';
        List<Idol__c> idols = Database.query('SELECT '+ retrieveFields +
                                                ' FROM ' + fieldLocation +
                                                ' ORDER BY '+ sortOrder+ ' ASC');
        
        return idols;
    }

    public void sortByDateRecruited(){
        this.sortOrder = 'Date_recruited__c';
    }
    public void sortName(){
        this.sortOrder = 'Name';
    }
    public void sortAssignedLocation(){
        this.sortOrder = 'Assigned_Location__c';
    }
    public void sortIdolPay() {
        this.sortOrder = 'Idol_Pay__c';
    }

    public PageReference Create(){
        PageReference page = new PageReference('/apex/CreatedIdolPage');
        page.setRedirect(true);
        return page;
    }
    public PageReference Back(){
        PageReference page = new PageReference('/apex/IdolVisualForcePage');
        page.setRedirect(true);
        return page;
    }
    public PageReference SaveMessage(){
        insert idol; 
        PageReference page = new PageReference('/apex/IdolCreatedMessage');
        page.setRedirect(true);
        return page;
    }
    
}