force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol__c/fields/Idol_phone__c.field-meta.xml
<CustomField>
    <fullName>Idol_phone__c</fullName>
    <label>Idol phone number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Idol__c/recordTypes/Idol.recordType-meta.xml
<RecordType>
    <fullName>Idol</fullName>
    <active>true</active>
    <description>Fully fledged Idols that have debuted</description>
    <label>Idol</label>
</RecordType>

force-app/main/default/objects/Idol_Group__c/Idol_Group__c.object-meta.xml
<CustomObject>
    <label>Idol Group</label>
    <nameField>
        <label>Idol Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idol Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol_Group__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <description>The group&apos;s leading member</description>
    <label>Lead</label>
    <referenceTo>Idol__c</referenceTo>
    <relationshipLabel>Idol Groups (Idol)</relationshipLabel>
    <relationshipName>Idol_Management</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Idol_Group__c/fields/Vocals__c.field-meta.xml
<CustomField>
    <fullName>Vocals__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The main vocal talent of the group</description>
    <label>Vocals</label>
    <referenceTo>Idol__c</referenceTo>
    <relationshipLabel>Idol Groups (Idol_2)</relationshipLabel>
    <relationshipName>Idol_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/btsMockData.cls
@isTest
public with sharing class btsMockData {
   
   public static List <Idol__c> createIdol(Integer num) {

    List<Idol__c> idolList = new List<Idol__c>();
    for (Integer i = 0; i < num; i++) {
        Idol__c idol = new Idol__c(name='test' + i, Idol_phone__c = '5555555555' + 1);
        idolList.add(idol);
    }

    insert idolList;
    List<Idol__c> masteridolList = [SELECT Name, (SELECT NAME FROM Idol_Groups__r WHERE Name='bts') FROM Idol__c];
    return masteridolList;

    }

    public static List <Idol_Group__c> createIdolGroup(Integer num, Id idolId) {

    List<Idol_Group__c> groupList = new List<Idol_Group__c>();
    for (Integer i = 0; i < num; i++) {
        Idol_Group__c grup = new Idol_Group__c(name='bts', Lead__c = idolId, Vocals__c=idolId);
        groupList.add(grup);

    }

    insert groupList;
    return groupList;



}
}