force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol__c/fields/Assigned_Location__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Idols</relationshipLabel>
    <relationshipName>Idols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Idol__c/fields/Date_recruited__c.field-meta.xml
<CustomField>
    <fullName>Date_recruited__c</fullName>
    <label>Date recruited</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Idol__c/fields/Idol_Pay__c.field-meta.xml
<CustomField>
    <fullName>Idol_Pay__c</fullName>
    <label>Idol Pay</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Idol__c/fields/Idol_phone__c.field-meta.xml
<CustomField>
    <fullName>Idol_phone__c</fullName>
    <label>Idol phone number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Idol__c/recordTypes/Idol.recordType-meta.xml
<RecordType>
    <fullName>Idol</fullName>
    <active>true</active>
    <description>Fully fledged Idols that have debuted</description>
    <label>Idol</label>
</RecordType>

force-app/main/default/classes/IdolControllerExtensionTest.cls
@isTest
public class IdolControllerExtensionTest {
    @isTest static void VerifySave(){
        //cummy idol controller
        Idol__c idol = new Idol__c();
        //calls the current page
        Test.setCurrentPage(Page.CreatedIdolPage);
        //Create a standard controller with the dummy controller
        ApexPages.StandardController idolController = new ApexPages.StandardController(idol);
        
        //Get the standard controller and pass it through the controller extension
        IdolControllerExtension test = new IdolControllerExtension(idolController);
        
        System.Test.StartTest();
        test.idol.Name = 'Testing';
        test.idol.Idol_Pay__c = 12341;
        test.idol.Idol_phone__c = '1231231234';
        PageReference testPage = test.SaveMessage(); 
        System.Test.StopTest();
        
        Idol__c verifyIdolInsert = [SELECT Name FROM Idol__c WHERE Name = 'Testing'];
        System.assert(verifyIdolInsert != NULL);
        
        System.assertEquals('/apex/IdolCreatedMessage', testPage.getUrl());
    }
    @isTest static void VerifyBack(){
        //cummy idol controller
        Idol__c idol = new Idol__c();
        //calls the current page
        Test.setCurrentPage(Page.IdolCreatedMessage);
        //Create a standard controller with the dummy controller
        ApexPages.StandardController idolController = new ApexPages.StandardController(idol);
        
        //Get the standard controller and pass it through the controller extension
        IdolControllerExtension test = new IdolControllerExtension(idolController);
        
        System.Test.StartTest();
        PageReference testPage = test.Back(); 
        System.Test.StopTest();
        
        System.assertEquals('/apex/IdolVisualForcePage', testPage.getUrl());
    }
    @isTest static void VerifyCreate(){
        //cummy idol controller
        Idol__c idol = new Idol__c();
        //calls the current page
        Test.setCurrentPage(Page.IdolVisualForcePage);
        //Create a standard controller with the dummy controller
        ApexPages.StandardController idolController = new ApexPages.StandardController(idol);
        
        //Get the standard controller and pass it through the controller extension
        IdolControllerExtension test = new IdolControllerExtension(idolController);
        
        System.Test.StartTest();
        PageReference testPage = test.Create(); 
        System.Test.StopTest();
        
        System.assertEquals('/apex/IdolVisualForcePage', testPage.getUrl());
    }
    @isTest static void VerifyGetIdol(){
        //cummy idol controller
        Idol__c idol = new Idol__c();
        //calls the current page
        Test.setCurrentPage(Page.IdolVisualForcePage);
        //Create a standard controller with the dummy controller
        ApexPages.StandardController idolController = new ApexPages.StandardController(idol);
        
        //Get the standard controller and pass it through the controller extension
        IdolControllerExtension test = new IdolControllerExtension(idolController);
        
        String sortOrder = 'Name';
        String retrieveFields = 'Name, Id, Idol_Phone__c, Assigned_Location__c, Date_recruited__c, Idol_Pay__c';
        String fieldLocation = 'Idol__c';
        List<Idol__c> idols = Database.query('SELECT '+ retrieveFields +
                                                ' FROM ' + fieldLocation +
                                                ' ORDER BY '+ sortOrder+ ' ASC');
        System.Test.StartTest();
        List<Idol__c> testIdol = test.getIdols();	
        System.Test.StopTest();
        
        System.assertEquals(idols, testIdol);
    }
    
}