force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol_Group__c/Idol_Group__c.object-meta.xml
<CustomObject>
    <label>Idol Group</label>
    <nameField>
        <label>Idol Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idol Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol_Group__c/fields/Vocals__c.field-meta.xml
<CustomField>
    <fullName>Vocals__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The main vocal talent of the group</description>
    <label>Vocals</label>
    <referenceTo>Idol__c</referenceTo>
    <relationshipLabel>Idol Groups (Idol_2)</relationshipLabel>
    <relationshipName>Idol_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/blackpinkControllerTest.cls
@isTest
public with sharing class blackpinkControllerTest {


   @isTest static void blackpinkControllerTest() {

     List<Idol__c> var = blackpinkMockData.createIdol(1);
     Idol__c variablename = [SELECT ID FROM Idol__c LIMIT 1];
     ID varID = variablename.ID;



     List<Idol_Group__c> lis = blackpinkMockData.createIdolGroup(1, varID);

     List<Idol__c> expected = [SELECT Name, (SELECT NAME FROM Idol_Groups__r WHERE Name='black') FROM Idol__c];
     



     Test.startTest();
     blackpinkController bp = new blackpinkController();
     List<Idol__c> actual = bp.blackpinkController();
     Test.stopTest();
     

     System.assertEquals(expected, actual );
      

}

}