force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idol__c/recordTypes/Idol.recordType-meta.xml
<RecordType>
    <fullName>Idol</fullName>
    <active>true</active>
    <description>Fully fledged Idols that have debuted</description>
    <label>Idol</label>
</RecordType>

force-app/main/default/objects/Idol_Group__c/Idol_Group__c.object-meta.xml
<CustomObject>
    <label>Idol Group</label>
    <nameField>
        <label>Idol Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idol Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Relations__c/Public_Relations__c.object-meta.xml
<CustomObject>
    <label>Public Relation</label>
    <nameField>
        <label>PR event name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Relations__c/fields/Idol__c.field-meta.xml
<CustomField>
    <fullName>Idol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Idol</label>
    <referenceTo>Idol__c</referenceTo>
    <relationshipLabel>Public Relations</relationshipLabel>
    <relationshipName>Public_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Relations__c/fields/Idol_Group__c.field-meta.xml
<CustomField>
    <fullName>Idol_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Idol Group</label>
    <referenceTo>Idol_Group__c</referenceTo>
    <relationshipLabel>Public Relations</relationshipLabel>
    <relationshipName>Public_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/pickIdols_CC.cls
public class pickIdols_CC {


    public String selectedIdolId{get; set;}
    public List<Public_Relations__c> prRecords{get; set;}

        
    public List<SelectOption> getIdolNames(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Select--'));
        for(Idol__c idol : [SELECT Id,Name from Idol__c]){
            options.add(new SelectOption(idol.Id,idol.Name));
        }
        return options;
    }
    
    public void ShowTable(){
        System.debug('Selected Idol Id -> ' + selectedIdolId);
        prRecords = [SELECT Name, Date__c, Idol__c, Idol_Group__c, Details__c, id FROM Public_Relations__c WHERE Idol__c=:selectedIdolId];

    }
    

    

}